name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.2
      

      
    - name: Install dependencies
      run: dotnet restore SQTest/SQTest.sln
    - name: Install SQ.MSBuild
      run: dotnet tool install dotnet-sonarscanner -g
    - name: Sonar Prepare
      run: dotnet-sonarscanner begin /k:devopsdylan_SQTest /o:devopsdylan /d:sonar.verbose=true /d:sonar.login=eb7cced101d71bbe6d3f1b35754977faca7b6627
    - name: Build
      run: dotnet build SQTest/SQTest.sln --configuration Release --no-restore
