name: Release Validation

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Release Files
      run: gh release download ${{ github.event.release.name }} --dir release_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print all files
      run: dir /S
