name: Release Validation

on:
  release:
    types: [published, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Release Files
      run: gh release download ${{ github.event.release.name }} --dir release_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Validate Release Files
      uses: dylan-smith/validate-release-files@master
