name: Workflow Testing

on:
  push:
  pull_request:
    branches: [ master, dylan-smith-patch-3 ]
  workflow_dispatch:
     inputs:
      skipBuild:
        description: 'Skip the build? (true/false)'     
        required: true
        default: 'false'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: printenv
    - run: "echo base_ref: ${{ github.base_ref }}"
    - run: "echo ${{ github.event }}"
    - run: "echo event_path: ${{ github.event_path }}"
    - run: "echo head_ref: ${{ github.head_ref }}"
    - run: "echo repository: ${{ github.repository }}"
    - run: "echo RUNNING A BUILD"
      if: github.event.inputs.skipBuild == false
    - run: "echo SKIPPING THE BUILD"
      if: github.event.inputs.skipBuild == true
      
